In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [14]:
from sklearn.feature_extraction.text import CountVectorizer


In [15]:
data = pd.read_csv('https://raw.githubusercontent.com/galvin-mj/DAT_ATL_15/master/Datasets/yelp.csv')

In [16]:
data.head()
del data['Unnamed: 0']

In [17]:
data_subset = data[(data['stars']==1)|(data['stars']==5)]
data_subset.head()

business_id        date               review_id  stars  \
0  9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1  ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
3  _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4  6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   
6  zp713qNhx8d9KCJJnrw1xA  2010-02-12  riFQ3vxNpP4rWLk_CSri2A      5   

                                                text    type  \
0  My wife took me here on my birthday for breakf...  review   
1  I have no idea why some people give bad review...  review   
3  Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4  General Manager Scott Petello is a good egg!!!...  review   
6  Drop what you're doing and drive here. After I...  review   

                  user_id  cool  useful  funny  
0  rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1  0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
3  uZetl9T0NcROGOyFfughhg     1       2      0  
4  vYmM4KTsC8ZfQBg-j5MWkw     0       0      0  
6  wFweIWhv2fREZV_dYkz_1g     7       7      4

In [18]:
from sklearn.cross_validation import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data_subset['text'], data_subset['stars'])



In [19]:
vectorizer = CountVectorizer()
x_train_counts= vectorizer.fit_transform(x_train)
x_test_counts = vectorizer.transform(x_test)
x_train_counts.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [41]:
from sklearn import naive_bayes
nb_clf = naive_bayes.MultinomialNB()
nb_clf.fit(x_train_counts.toarray(), y_train)
prediction = nb_clf.predict(x_test_counts.toarray())
nb_clf.score(x_test_counts, y_test)



0.92074363992172215

In [40]:
from sklearn import metrics
metrics.confusion_matrix(y_test, prediction, labels=[1,5])

array([[131,  64],
       [ 17, 810]])

In [50]:
vectorizer2 = CountVectorizer(stop_words='english')
x_train_counts2= vectorizer2.fit_transform(x_train)
x_test_counts2 = vectorizer2.transform(x_test)
x_train_counts2.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:
nb_clf2 = naive_bayes.MultinomialNB()
nb_clf2.fit(x_train_counts2.toarray(), y_train)
prediction = nb_clf2.predict(x_test_counts2.toarray())
nb_clf2.score(x_test_counts2, y_test)

0.91878669275929548

In [56]:
vectorizer3 = CountVectorizer(min_df=2)
x_train_counts3= vectorizer3.fit_transform(x_train)
x_test_counts3 = vectorizer3.transform(x_test)
x_train_counts3.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [57]:
nb_clf3 = naive_bayes.MultinomialNB()
nb_clf3.fit(x_train_counts3.toarray(), y_train)
prediction = nb_clf3.predict(x_test_counts3.toarray())
nb_clf3.score(x_test_counts3, y_test)

0.9227005870841487

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer4 = TfidfVectorizer()
x_train_counts4 = vectorizer4.fit_transform(x_train)
x_test_counts4 = vectorizer4.transform(x_test)
x_train_counts4.toarray()

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [59]:
nb_clf4 = naive_bayes.MultinomialNB()
nb_clf4.fit(x_train_counts4.toarray(), y_train)
prediction = nb_clf4.predict(x_test_counts4.toarray())
nb_clf4.score(x_test_counts4, y_test)

0.80919765166340507

In [78]:
from sklearn.feature_extraction.text import TfidfTransformer
vectorizer5 = CountVectorizer()
transformer = TfidfTransformer()
tfidf1 = transformer.fit_transform(vectorizer5.fit_transform(x_train))
tfidf2 = transformer.fit_transform(vectorizer5.transform(x_test))

nb_clf5 = naive_bayes.MultinomialNB()
nb_clf5.fit(tfidf1.toarray(), y_train)
prediction = nb_clf5.predict(tfidf2.toarray())
nb_clf4.score(tfidf2, y_test)

0.80919765166340507

In [64]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

pipe = Pipeline([('logreg', LogisticRegression())])
pipe.fit(x_train_counts, y_train)
pipe.predict(x_test_counts)
pipe.score(x_test_counts, y_test)

0.93737769080234834

In [74]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train_counts, y_train)
knn.score(x_test_counts, y_test)


0.82485322896281799

In [81]:
from sklearn.grid_search import GridSearchCV


pipe2 = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('clf', LogisticRegression())
        
    ])

parameters = {
    'vect__max_df':(0.5,0.75,1.0),
    'vect__ngram_range': ((1,1),(2,2)),
    'clf_C': (0.00001, 0.5, 1.0),
    'clf_penalty': ('l1','l2')
    
}

In [84]:
grid_search = GridSearchCV(pipe2, parameters, n_jobs=-1, verbose=1)
